# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TokenForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TokenForm(object):
    def setupUi(self, TokenForm):
        TokenForm.setObjectName("TokenForm")
        TokenForm.setEnabled(True)
        TokenForm.resize(500, 52)
        TokenForm.setMaximumSize(QtCore.QSize(500, 52))
        TokenForm.setAccessibleName("")
        TokenForm.setAutoFillBackground(False)
        TokenForm.setSizeGripEnabled(False)
        self.TokenInput = QtWidgets.QLineEdit(TokenForm)
        self.TokenInput.setGeometry(QtCore.QRect(10, 10, 371, 31))
        self.TokenInput.setObjectName("TokenInput")
        self.TokenButton = QtWidgets.QPushButton(TokenForm)
        self.TokenButton.setGeometry(QtCore.QRect(380, 10, 113, 32))
        self.TokenButton.setObjectName("TokenButton")

        self.retranslateUi(TokenForm)
        QtCore.QMetaObject.connectSlotsByName(TokenForm)

    def retranslateUi(self, TokenForm):
        _translate = QtCore.QCoreApplication.translate
        TokenForm.setWindowTitle(_translate("TokenForm", "Git Token Input"))
        self.TokenButton.setText(_translate("TokenForm", "Enter"))
